use std::fmt;

/// Stable identity of a terminal block.
#[derive(Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct BlockId(String);

impl BlockId {
    /// Return the serialized block identity.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Create an identity supplied by a trusted protocol or application path.
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    /// Create a terminal block identity namespaced by session and shell.
    pub fn terminal(
        session_id: &TerminalSessionId,
        shell_instance_id: &ShellInstanceId,
        sequence: u64,
    ) -> Self {
        Self(format!(
            "{}:{}:{sequence}",
            session_id.as_str(),
            shell_instance_id.as_str()
        ))
    }
}

impl fmt::Display for BlockId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// Identity shared by all shell contexts in one terminal session.
#[derive(Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct TerminalSessionId(String);

impl TerminalSessionId {
    /// Return the serialized session identity.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Create an identity generated by the application bootstrap path.
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }
}

impl fmt::Display for TerminalSessionId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// Stable identity of one root or nested shell process.
#[derive(Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ShellInstanceId(String);

impl ShellInstanceId {
    /// Return the serialized shell identity.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Create an identity supplied by a validated shell event.
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }
}

impl fmt::Display for ShellInstanceId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// Monotonic ordering value for events emitted by one shell instance.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ProtocolSequence(u64);

impl ProtocolSequence {
    /// Return the numeric ordering value.
    pub fn value(self) -> u64 {
        self.0
    }

    /// Create a sequence value from a validated protocol field.
    pub fn new(value: u64) -> Self {
        Self(value)
    }

    pub(super) fn next(self) -> Option<Self> {
        self.0.checked_add(1).map(Self)
    }
}

impl fmt::Display for ProtocolSequence {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[cfg(test)]
mod tests {
    use super::{
        BlockId, ProtocolSequence, ShellInstanceId, TerminalSessionId,
    };

    #[test]
    fn terminal_block_id_contains_all_identity_parts() {
        let session = TerminalSessionId::new("session-a");
        let shell = ShellInstanceId::new("shell-b");

        let id = BlockId::terminal(&session, &shell, 42);

        assert_eq!(id.as_str(), "session-a:shell-b:42");
    }

    #[test]
    fn protocol_sequence_exposes_ordering_value() {
        let first = ProtocolSequence::new(1);
        let second = ProtocolSequence::new(2);

        assert!(first < second);
        assert_eq!(second.value(), 2);
    }
}
