use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use otty_ui_term::settings::{LocalSessionOptions, SessionKind};

const FALLBACK_SHELL: &str = "/bin/bash";
const SHELL_INTEGRATIONS_DIR: &str = "otty";

const OTTY_ZSH_SCRIPT: &str =
    include_str!("../../../assets/shell-integrations/otty.zsh");
const OTTY_BASH_SCRIPT: &str =
    include_str!("../../../assets/shell-integrations/otty.bash");

fn config_dir() -> PathBuf {
    if let Ok(home) = env::var("HOME") {
        return Path::new(&home)
            .join(".config")
            .join(SHELL_INTEGRATIONS_DIR);
    }

    env::temp_dir().join(SHELL_INTEGRATIONS_DIR)
}

pub fn setup_shell_session() -> std::io::Result<(String, SessionKind)> {
    let shell_path =
        env::var("SHELL").unwrap_or_else(|_| FALLBACK_SHELL.to_string());

    let shell_name = Path::new(&shell_path)
        .file_name()
        .and_then(|name| name.to_str())
        .map(ToString::to_string)
        .unwrap_or_else(|| shell_path.clone());

    let dir = config_dir();
    // Ensure directory
    fs::create_dir_all(&dir)?;

    let session = match shell_name.as_str() {
        "zsh" => setup_zsh_session(&shell_path, &dir)?,
        "bash" => setup_bash_session(&shell_path, &dir)?,
        _ => {
            let options =
                LocalSessionOptions::default().with_program(&shell_path);
            SessionKind::from_local_options(options)
        },
    };

    Ok((shell_name, session))
}

fn setup_zsh_session(
    shell_path: &str,
    dir: &Path,
) -> std::io::Result<SessionKind> {
    let original_zdotdir = env::var("ZDOTDIR").ok();

    let script_path = dir.join("otty.zsh");
    fs::write(&script_path, OTTY_ZSH_SCRIPT)?;

    let zshrc_path = dir.join(".zshrc");
    let zshrc_contents = r#"
# Generated by OTTY: wrapper around user zshrc
if [[ -n "${OTTY_ORIG_ZDOTDIR:-}" && "${OTTY_ORIG_ZDOTDIR}" != "${ZDOTDIR:-$HOME}" && -f "${OTTY_ORIG_ZDOTDIR}/.zshrc" ]]; then
  source "${OTTY_ORIG_ZDOTDIR}/.zshrc"
elif [[ -f "${HOME}/.zshrc" ]]; then
  source "${HOME}/.zshrc"
fi

if [[ -f "${ZDOTDIR:-$HOME}/otty.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/otty.zsh"
fi
"#;

    fs::write(&zshrc_path, zshrc_contents.trim_start())?;

    let mut options = LocalSessionOptions::default()
        .with_program(shell_path)
        .with_env("ZDOTDIR", &dir.to_string_lossy());

    if let Some(value) = original_zdotdir {
        if Path::new(&value) != dir {
            options = options.with_env("OTTY_ORIG_ZDOTDIR", &value);
        }
    }

    Ok(SessionKind::from_local_options(options))
}

fn setup_bash_session(
    shell_path: &str,
    dir: &Path,
) -> std::io::Result<SessionKind> {
    let script_path = dir.join("otty.bash");
    fs::write(&script_path, OTTY_BASH_SCRIPT)?;

    let wrapper_path = dir.join("otty.bashrc");
    let wrapper_contents = format!(
        r#"# Generated by OTTY: wrapper around user bashrc
if [[ -f "$HOME/.bashrc" ]]; then
  source "$HOME/.bashrc"
fi

if [[ -f "{script}" ]]; then
  source "{script}"
fi
"#,
        script = script_path.to_string_lossy()
    );

    fs::write(&wrapper_path, wrapper_contents.trim_start())?;

    let options = LocalSessionOptions::default()
        .with_program(shell_path)
        .with_args(vec![
            "--rcfile".to_string(),
            wrapper_path.to_string_lossy().to_string(),
        ]);

    Ok(SessionKind::from_local_options(options))
}
