//! Bootstrap local shell sessions with OTTY shell integrations.

use std::fmt::Write as _;
use std::fs::{File, OpenOptions};
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::{env, fs};

use thiserror::Error;

const SHELL_INTEGRATIONS_DIR: &str = "otty";
const SHELL_INTEGRATION_VERSION: &str = "v2";
const TERMINAL_SESSION_RANDOM_BYTES: usize = 16;

static TEMP_FILE_SEQUENCE: AtomicU64 = AtomicU64::new(0);

const OTTY_ZSH_SCRIPT: &str =
    include_str!("../../../assets/shell-integrations/otty.zsh");
const OTTY_BASH_SCRIPT: &str =
    include_str!("../../../assets/shell-integrations/otty.bash");

/// Process launch data for a shell prepared with OTTY integrations.
#[derive(Debug, Clone)]
pub struct ShellLaunch {
    name: String,
    program: String,
    args: Vec<String>,
    envs: Vec<(String, String)>,
}

impl ShellLaunch {
    /// Return the shell label suitable for terminal tab titles.
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Return the shell executable path.
    pub fn program(&self) -> &str {
        &self.program
    }

    /// Return the arguments passed to the shell executable.
    pub fn args(&self) -> &[String] {
        &self.args
    }

    /// Return environment variables added by shell bootstrap.
    pub fn envs(&self) -> &[(String, String)] {
        &self.envs
    }

    fn new(name: String, program: String) -> Self {
        Self {
            name,
            program,
            args: Vec::new(),
            envs: Vec::new(),
        }
    }
}

/// Errors produced while preparing shell integration files.
#[derive(Debug, Error)]
pub enum ShellBootstrapError {
    /// Shell integration file setup failed.
    #[error("shell integration IO failed")]
    Io(#[from] std::io::Error),
}

/// Build process launch data with OTTY integrations for a given shell.
///
/// Unsupported shells still receive runnable process data marked through
/// the `OTTY_INTEGRATION_UNSUPPORTED` environment variable.
///
/// # Errors
///
/// Returns [`ShellBootstrapError`] when the integration directory or files
/// cannot be prepared.
///
/// # Examples
///
/// ```no_run
/// use otty_shell_bootstrap::setup_shell_launch_with_shell;
///
/// let launch = setup_shell_launch_with_shell("/bin/bash")?;
/// assert_eq!(launch.name(), "bash");
/// # Ok::<(), otty_shell_bootstrap::ShellBootstrapError>(())
/// ```
pub fn setup_shell_launch_with_shell(
    shell_path: &str,
) -> Result<ShellLaunch, ShellBootstrapError> {
    let shell_name = shell_name(shell_path);

    let dir = config_dir();
    fs::create_dir_all(&dir)?;

    let launch = match shell_name.as_str() {
        "zsh" => setup_zsh_launch(shell_path, &dir)?,
        "bash" => setup_bash_launch(shell_path, &dir)?,
        _ => {
            let mut launch =
                ShellLaunch::new(shell_name, shell_path.to_string());
            launch.envs.push((
                String::from("OTTY_INTEGRATION_UNSUPPORTED"),
                launch.name.clone(),
            ));
            launch
        },
    };

    Ok(launch)
}

/// Build process launch data without writing integration files.
///
/// # Examples
///
/// ```
/// use otty_shell_bootstrap::fallback_shell_launch_with_shell;
///
/// let launch = fallback_shell_launch_with_shell("/bin/sh");
/// assert_eq!(launch.name(), "sh");
/// ```
pub fn fallback_shell_launch_with_shell(shell_path: &str) -> ShellLaunch {
    let mut launch =
        ShellLaunch::new(shell_name(shell_path), shell_path.to_string());
    launch.envs.push((
        String::from("OTTY_INTEGRATION_DEGRADED"),
        String::from("bootstrap_failed"),
    ));

    launch
}

fn shell_name(shell_path: &str) -> String {
    Path::new(shell_path)
        .file_name()
        .and_then(|name| name.to_str())
        .map(ToString::to_string)
        .unwrap_or_else(|| shell_path.to_string())
}

fn config_dir() -> PathBuf {
    if let Ok(home) = env::var("HOME") {
        return Path::new(&home)
            .join(".config")
            .join(SHELL_INTEGRATIONS_DIR);
    }

    env::temp_dir().join(SHELL_INTEGRATIONS_DIR)
}

fn setup_zsh_launch(
    shell_path: &str,
    dir: &Path,
) -> std::io::Result<ShellLaunch> {
    let original_zdotdir = env::var("ZDOTDIR").ok();
    let terminal_session_id = generate_terminal_session_id()?;

    let script_path = integration_asset_path(dir, "otty.zsh");
    atomic_write_if_changed(&script_path, OTTY_ZSH_SCRIPT.as_bytes())?;

    let zshrc_path = dir.join(".zshrc");
    let script_path_display = script_path.to_string_lossy();
    let script_path_shell = shell_words::quote(script_path_display.as_ref());
    let zshrc_contents = r#"
# Generated by OTTY: wrapper around user zshrc
if [[ -n "${OTTY_ORIG_ZDOTDIR:-}" && "${OTTY_ORIG_ZDOTDIR}" != "${ZDOTDIR:-$HOME}" && -f "${OTTY_ORIG_ZDOTDIR}/.zshrc" ]]; then
  source "${OTTY_ORIG_ZDOTDIR}/.zshrc"
elif [[ -f "${HOME}/.zshrc" ]]; then
  source "${HOME}/.zshrc"
fi

if [[ -f __OTTY_SCRIPT_PATH__ ]]; then
  source __OTTY_SCRIPT_PATH__
fi
"#
    .replace("__OTTY_SCRIPT_PATH__", script_path_shell.as_ref());

    atomic_write_if_changed(
        &zshrc_path,
        zshrc_contents.trim_start().as_bytes(),
    )?;

    let mut launch =
        ShellLaunch::new(shell_name(shell_path), shell_path.to_string());
    launch.envs.extend([
        (String::from("ZDOTDIR"), dir.to_string_lossy().into_owned()),
        (
            String::from("OTTY_TERMINAL_SESSION_ID"),
            terminal_session_id,
        ),
        (String::from("OTTY_INTEGRATION_VERSION"), String::from("2")),
    ]);

    if let Some(value) = original_zdotdir
        && Path::new(&value) != dir
    {
        launch.envs.push((String::from("OTTY_ORIG_ZDOTDIR"), value));
    }

    Ok(launch)
}

fn setup_bash_launch(
    shell_path: &str,
    dir: &Path,
) -> std::io::Result<ShellLaunch> {
    let terminal_session_id = generate_terminal_session_id()?;
    let script_path = integration_asset_path(dir, "otty.bash");
    atomic_write_if_changed(&script_path, OTTY_BASH_SCRIPT.as_bytes())?;

    let wrapper_path = dir.join("otty-v2.bashrc");
    let script_path_display = script_path.to_string_lossy();
    let wrapper_contents = format!(
        r#"# Generated by OTTY: wrapper around user bashrc
if [[ -f "$HOME/.bashrc" ]]; then
  source "$HOME/.bashrc"
fi

if [[ -f "{script_path_display}" ]]; then
  source "{script_path_display}"
fi
"#
    );

    atomic_write_if_changed(
        &wrapper_path,
        wrapper_contents.trim_start().as_bytes(),
    )?;

    let mut launch =
        ShellLaunch::new(shell_name(shell_path), shell_path.to_string());
    launch.args = vec![
        String::from("--rcfile"),
        wrapper_path.to_string_lossy().into_owned(),
    ];
    launch.envs = vec![
        (
            String::from("OTTY_TERMINAL_SESSION_ID"),
            terminal_session_id,
        ),
        (String::from("OTTY_INTEGRATION_VERSION"), String::from("2")),
    ];

    Ok(launch)
}

fn integration_asset_path(dir: &Path, file_name: &str) -> PathBuf {
    dir.join("shell-integrations")
        .join(SHELL_INTEGRATION_VERSION)
        .join(file_name)
}

fn generate_terminal_session_id() -> std::io::Result<String> {
    let mut random = [0_u8; TERMINAL_SESSION_RANDOM_BYTES];
    File::open("/dev/urandom")?.read_exact(&mut random)?;

    let mut encoded = String::with_capacity(TERMINAL_SESSION_RANDOM_BYTES * 2);
    for byte in random {
        write!(encoded, "{byte:02x}").map_err(std::io::Error::other)?;
    }

    Ok(encoded)
}

fn atomic_write_if_changed(
    path: &Path,
    contents: &[u8],
) -> std::io::Result<()> {
    if fs::read(path).is_ok_and(|current| current == contents) {
        return ensure_private_permissions(path);
    }

    let Some(parent) = path.parent() else {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "integration asset path has no parent",
        ));
    };
    fs::create_dir_all(parent)?;

    let sequence = TEMP_FILE_SEQUENCE.fetch_add(1, Ordering::Relaxed);
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("otty-integration");
    let temporary_path = parent.join(format!(
        ".{file_name}.tmp-{}-{sequence}",
        std::process::id()
    ));
    let write_result = write_temporary_file(&temporary_path, contents)
        .and_then(|()| fs::rename(&temporary_path, path));

    if write_result.is_err() {
        let _ = fs::remove_file(&temporary_path);
    }

    write_result?;
    ensure_private_permissions(path)
}

#[cfg(unix)]
fn ensure_private_permissions(path: &Path) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;

    fs::set_permissions(path, fs::Permissions::from_mode(0o600))
}

#[cfg(not(unix))]
fn ensure_private_permissions(_path: &Path) -> std::io::Result<()> {
    Ok(())
}

fn write_temporary_file(path: &Path, contents: &[u8]) -> std::io::Result<()> {
    let mut options = OpenOptions::new();
    options.write(true).create_new(true);

    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(0o600);
    }

    let mut file = options.open(path)?;
    file.write_all(contents)?;
    file.sync_all()
}

#[cfg(test)]
mod tests;
