name: Security Audit

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read

env:
  rust_stable: "1.96"

jobs:
  cargo-deny:
    permissions:
      checks: write
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install Rust ${{ env.rust_stable }}
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.rust_stable }}
    - uses: EmbarkStudios/cargo-deny-action@v2
