name: Lint

on:
  pull_request:
  push:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  FmtCheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust ${{ vars.RUST_NIGHTLY_TOOLCHAIN }}
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ vars.RUST_NIGHTLY_TOOLCHAIN }}
        components: clippy, rustfmt
    - run: cargo +${{ vars.RUST_NIGHTLY_TOOLCHAIN }} fmt --all -- --check

  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ vars.RUST_STABLE_TOOLCHAIN }}
    - run: cargo lint
