name: Lint

on:
  pull_request:
  push:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

env:
  rust_stable: "1.96"
  rust_nightly: "nightly-2026-03-10"

jobs:
  FmtCheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust ${{ env.rust_nightly }}
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.rust_nightly }}
        components: clippy, rustfmt
    - run: cargo +${{ env.rust_nightly }} fmt --all -- --check

  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust ${{ env.rust_stable }}
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.rust_stable }}
    - run: cargo lint
